import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Providers from "./providers";
import "antd/dist/reset.css";
import "./globals.css";
import "./ckeditor-overrides.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Deutsche Wealth Online",
  description: "Generated by Deutsche Wealth Online",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import Providers from "./providers";
// import "antd/dist/reset.css";
// import { Roboto } from "next/font/google";
// import "./globals.css";

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "700"],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Deutsche Wealth Online",
//   description: "Generated by Deutsche Wealth Online",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`roboto.className ${geistSans.variable} ${geistMono.variable}`}
//       >
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }
