export const titles = ["Mr", "Mrs", "Miss", "Ms", "Dr", "Rev", "Other"];

export const regions = [
  "Aberdeenshire",
  "Angus",
  "Argyll and Bute",
  "Avon",
  "Barking and Dagenham",
  "Barnet",
  "Barnsley",
  "Bath and North East Somerset",
  "Bedfordshire",
  "Berkshire",
  "Bexley",
  "Birmingham",
  "Blackburn with Darwen",
  "Blackpool",
  "Blaenau Gwent",
  "Bolton",
  "Bournemouth",
  "Bracknell Forest",
  "Bradford",
  "Brent",
  "Bridgend",
  "Brighton and Hove",
  "Bromley",
  "Buckinghamshire",
  "Bury",
  "Caerphilly",
  "Calderdale",
  "Cambridgeshire",
  "Camden",
  "Cardiff",
  "Carmarthenshire",
  "Ceredigion",
  "Cheshire",
  "City of Bristol",
  "City of Edinburgh",
  "City of Kingston upon Hull",
  "City of London",
  "Clackmannanshire",
  "Cleveland",
  "Co. Antrim",
  "Co. Armagh",
  "Co. Down",
  "Co. Fermanagh",
  "Co. Londonderry",
  "Co. Tyrone",
  "Conwy",
  "Cornwall",
  "Coventry",
  "Croydon",
  "Cumbria",
  "Darlington",
  "Denbighshire",
  "Derby",
  "Derbyshire",
  "Devon",
  "Doncaster",
  "Dorset",
  "Dudley",
  "Dumfries and Galloway",
  "Dundee City",
  "Durham",
  "Ealing",
  "East Ayrshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Sussex",
  "Eilean Siar (Western Isles)",
  "Enfield",
  "Essex",
  "Falkirk",
  "Fife",
  "Flintshire",
  "Gateshead",
  "Glasgow City",
  "Gloucestershire",
  "Greenwich",
  "Gwynedd",
  "Hackney",
  "Halton",
  "Hammersmith and Fulham",
  "Hampshire",
  "Haringey",
  "Harrow",
  "Hartlepool",
  "Havering",
  "Herefordshire",
  "Hertfordshire",
  "Highland",
  "Hillingdon",
  "Hounslow",
  "Inverclyde",
  "Isle of Anglesey",
  "Isle of Wight",
  "Islington",
  "Kensington and Chelsea",
  "Kent",
  "Kingston upon Thames",
  "Kirklees",
  "Knowsley",
  "Lambeth",
  "Lancashire",
  "Leeds",
  "Leicester",
  "Leicestershire",
  "Lewisham",
  "Lincolnshire",
  "Liverpool",
  "London",
  "Luton",
  "Manchester",
  "Medway",
  "Merseyside",
  "Merthyr Tydfil",
  "Merton",
  "Middlesbrough",
  "Middlesex",
  "Midlothian",
  "Milton Keynes",
  "Monmouthshire",
  "Moray",
  "Neath Port Talbot",
  "Newcastle upon Tyne",
  "Newham",
  "Newport",
  "Norfolk",
  "North Ayrshire",
  "North East Lincolnshire",
  "North Humberside",
  "North Lanarkshire",
  "North Lincolnshire",
  "North Somerset",
  "North Tyneside",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottingham",
  "Nottinghamshire",
  "Oldham",
  "Orkney Islands",
  "Oxfordshire",
  "Pembrokeshire",
  "Perth and Kinross",
  "Peterborough",
  "Plymouth",
  "Poole",
  "Portsmouth",
  "Powys",
  "Reading",
  "Redbridge",
  "Renfrewshire",
  "Rhondda Cynon Taff",
  "Richmond upon Thames",
  "Rochdale",
  "Rotherham",
  "Rutland",
  "Salford",
  "Sandwell",
  "Sefton",
  "Sheffield",
  "Shetland Islands",
  "Shropshire",
  "Slough",
  "Solihull",
  "Somerset",
  "South Ayrshire",
  "South Gloucestershire",
  "South Humberside",
  "South Lanarkshire",
  "South Tyneside",
  "South Yorkshire",
  "Southampton",
  "Southend-on-Sea",
  "Southwark",
  "St. Helens",
  "Staffordshire",
  "Stirling",
  "Stockport",
  "Stockton-on-Tees",
  "Stoke-on-Trent",
  "Suffolk",
  "Sunderland",
  "Surrey",
  "Sutton",
  "Swansea",
  "Swindon",
  "Tameside",
  "Telford and Wrekin",
  "The Scottish Borders",
  "The Vale of Glamorgan",
  "Thurrock",
  "Torbay",
  "Torfaen",
  "Tower Hamlets",
  "Trafford",
  "Tyne and Wear",
  "Wakefield",
  "Walsall",
  "Waltham Forest",
  "Wandsworth",
  "Warrington",
  "Warwickshire",
  "West Dunbartonshire",
  "West Lothian",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Westminster",
  "Wigan",
  "Wiltshire",
  "Windsor and Maidenhead",
  "Wirral",
  "Wokingham",
  "Wolverhampton",
  "Worcestershire",
  "Wrexham",
  "York",
];
